version: '3.1'

services:
  api:
    container_name: eureka-server
    image: springcloud/eureka
    expose:
      - 8761
    ports:
      - 8761:8761
networks:
  default:
    external:
      name: microservices

